name: exercice de workflow on push 
run-name: ${{ github.actor }} is learning GitHub Actions
on:
    push:
        branches: 
            - main
jobs: 
    first_job: 
        name: first job on push
        runs-on: ubuntu-latest
        steps:
            - name: get the code !
              uses: actions/checkout@v4
            - name: installation des node_modules
              run: npm install
            - name: test du projet 
              run: npm run test
            - name: build du projet
              run: npm run build
            - name: upload le resultat du build 
              uses: actions/upload-artifact@v4
              with: 
                name: mon-site-pour-lexercice
                path: .dist/
    second_job: 
        needs: first_job
        name: second job on push
        runs-on: ubuntu-latest`
        steps: 
            - name: Get the artifact !
              uses: actions/download-artifact@v4
              with: 
                name: mon-site-pour-lexercice
                path: ./dist
            - name: List la liste
              run: |
                cd dist
                ls
        


        

